[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "panic=abort"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console", "-C", "panic=abort"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles", "-C", "panic=abort"]
